version: '2.4'
networks:
  cassandra:

services:
  cassandra-seed:
    image: cassandra  
    container_name: cassandra-seed
    hostname: cassandra-seed
    mem_limit: 3g
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra-seed:/var/lib/cassandra
    environment:
         AUTO_BOOTSTRAP: false
    environment: &environment
        CASSANDRA_SEEDS: "cassandra-seed,cassandra-node_1, cassandra-node_2"
        CASSANDRA_CLUSTER_NAME: test_cluster
        CASSANDRA_DC: datacenter
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128

  cassandra-node_1:
    image: cassandra
    container_name: cassandra-node_1
    hostname: cassandra-node_1
    mem_limit: 3g
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9043:9042"  
    volumes:
      - ./data/cassandra-node_1:/var/lib/cassandra 
    environment: *environment
    depends_on:
      cassandra-seed:
        condition: service_healthy

  cassandra-node_2:
    image: cassandra
    container_name: cassandra-node_2
    hostname: cassandra-node_2
    mem_limit: 3g
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9044:9042"
    volumes:
      - ./data/cassandra-node_2:/var/lib/cassandra 
    environment: *environment
    depends_on:
      cassandra-node_1:
        condition: service_healthy
